// AUTO-GENERATED by scripts/gen-fields.ts — do not edit
import { FieldRef } from "../fieldRef.js";

export const usersFields = {
  id: new FieldRef<string>("id"),
  last_billed_timestamp: new FieldRef<string>("last_billed_timestamp"),
  payment_provider_user_id: new FieldRef<string>("payment_provider_user_id"),
  mode: new FieldRef<string>("mode"),
} as const;

export const sessionsFields = {
  id: new FieldRef<string>("id"),
  session_id: new FieldRef<string>("session_id"),
  user_id: new FieldRef<string>("user_id"),
  processed: new FieldRef<string>("processed"),
  billed_upto: new FieldRef<string>("billed_upto"),
  created_at: new FieldRef<string>("created_at"),
  mode: new FieldRef<string>("mode"),
} as const;

export const tagsFields = {
  id: new FieldRef<string>("id"),
  key: new FieldRef<string>("key"),
  amount: new FieldRef<string>("amount"),
} as const;

export const expressionsFields = {
  id: new FieldRef<string>("id"),
  key: new FieldRef<string>("key"),
  expr: new FieldRef<string>("expr"),
} as const;

export const metadataFields = {
  id: new FieldRef<string>("id"),
  payment_cron: new FieldRef<string>("payment_cron"),
  payment_webhook: new FieldRef<string>("payment_webhook"),
} as const;
