// AUTO-GENERATED by scripts/gen-fields.ts — do not edit
import { FieldRef } from "../fieldRef.js";

export const sdkEventFields = {
  eventId: new FieldRef<string>("eventId"),
  eventType: new FieldRef<string>("eventType"),
  userId: new FieldRef<string>("userId"),
  reportedTimestamp: new FieldRef<string>("reportedTimestamp"),
  ingestedTimestamp: new FieldRef<string>("ingestedTimestamp"),
  apiKeyId: new FieldRef<string>("apiKeyId"),
  sdkCallType: new FieldRef<string>("sdkCallType"),
  debitAmount: new FieldRef<number>("debitAmount"),
} as const;

export const aiTokenFields = {
  eventId: new FieldRef<string>("eventId"),
  eventType: new FieldRef<string>("eventType"),
  userId: new FieldRef<string>("userId"),
  reportedTimestamp: new FieldRef<string>("reportedTimestamp"),
  ingestedTimestamp: new FieldRef<string>("ingestedTimestamp"),
  apiKeyId: new FieldRef<string>("apiKeyId"),
  model: new FieldRef<string>("model"),
  inputTokens: new FieldRef<number>("inputTokens"),
  outputTokens: new FieldRef<number>("outputTokens"),
  inputDebitAmount: new FieldRef<number>("inputDebitAmount"),
  outputDebitAmount: new FieldRef<number>("outputDebitAmount"),
} as const;

export const paymentFields = {
  eventId: new FieldRef<string>("eventId"),
  eventType: new FieldRef<string>("eventType"),
  userId: new FieldRef<string>("userId"),
  reportedTimestamp: new FieldRef<string>("reportedTimestamp"),
  ingestedTimestamp: new FieldRef<string>("ingestedTimestamp"),
  apiKeyId: new FieldRef<string>("apiKeyId"),
  creditAmount: new FieldRef<number>("creditAmount"),
} as const;
