/**
 * Codegen script: reads proto .d.ts files and generates field definitions.
 * 
 * Run: bun run scripts/gen-fields.ts
 * 
 * For event queries: reads EventRow.AsObject to get field names + types
 * For data queries: reads per-table proto enums to get field names
 * Maps proto camelCase property names → FieldRef instances
 */

import * as fs from "node:fs";
import * as path from "node:path";

const CORE_ROOT = path.resolve(__dirname, "..", "..", "scrawn");
const GEN_DIR = path.join(CORE_ROOT, "src", "gen");
const OUT_DIR = path.resolve(__dirname, "..", "src");

type FieldEntry = { name: string; type: string; protoName: string };

// ── Parse EventRow.AsObject from query_pb.d.ts ──

function parseQueryFields(): { sdkCall: FieldEntry[]; aiToken: FieldEntry[]; payment: FieldEntry[] } {
  const dts = fs.readFileSync(path.join(GEN_DIR, "query", "v1", "query_pb.d.ts"), "utf-8");
  
  // Extract EventRow.AsObject properties
  const eventRowMatch = dts.match(/export namespace EventRow \{\s*export type AsObject = \{([^}]+)\}/s);
  if (!eventRowMatch) throw new Error("Could not find EventRow.AsObject in query_pb.d.ts");

  const props = eventRowMatch[1];
  const fields: FieldEntry[] = [];
  const propRe = /(\w+)\??:\s*(\w+)/g;
  let m: RegExpExecArray | null;
  while ((m = propRe.exec(props)) !== null) {
    const [, name, type] = m;
    if (name === "sdkCallType" || name === "debitAmount") continue; // handled below
    if (fields.some(f => f.name === name)) continue;
    fields.push({ name, type, protoName: name });
  }

  // Map fields to specific groups based on what we know:
  // Common fields across all event types
  const common: FieldEntry[] = [
    ...fields.filter(f =>
      ["eventId", "eventType", "userId", "reportedTimestamp", "ingestedTimestamp"].includes(f.name)
    ),
    // apiKeyId returned by backend but missing from proto EventRow — TODO: add to proto
    { name: "apiKeyId", type: "string", protoName: "api_key_id" },
  ];

  const sdkCall: FieldEntry[] = [
    ...common,
    { name: "sdkCallType", type: "string", protoName: "sdk_call_type" },
    { name: "debitAmount", type: "number", protoName: "debit_amount" },
  ];

  const aiToken: FieldEntry[] = [
    ...common,
    { name: "model", type: "string", protoName: "model" },
    { name: "inputTokens", type: "number", protoName: "input_tokens" },
    { name: "outputTokens", type: "number", protoName: "output_tokens" },
    { name: "inputDebitAmount", type: "number", protoName: "input_debit_amount" },
    { name: "outputDebitAmount", type: "number", protoName: "output_debit_amount" },
  ];

  const payment: FieldEntry[] = [
    ...common,
    { name: "creditAmount", type: "number", protoName: "credit_amount" },
  ];

  return { sdkCall, aiToken, payment };
}

// ── Parse per-table enums from data_pb.d.ts ──

function parseTableName(enumName: string): string {
  // UsersFieldMap → users, SessionsFieldMap → sessions, etc.
  return enumName.replace("FieldMap", "").toLowerCase();
}

function parseDataFields(): Record<string, FieldEntry[]> {
  const dts = fs.readFileSync(path.join(GEN_DIR, "data", "v1", "data_pb.d.ts"), "utf-8");

  const tableFields: Record<string, FieldEntry[]> = {};
  
  // Find all FieldMap interfaces
  const enumRe = /export interface (\w+FieldMap) \{([^}]+)\}/gs;
  let m: RegExpExecArray | null;
  while ((m = enumRe.exec(dts)) !== null) {
    const enumName = m[1];
    const tableName = parseTableName(enumName);
    const body = m[2];

    const fields: FieldEntry[] = [];
    const memberRe = /(\w+):\s*(\d+)/g;
    let mm: RegExpExecArray | null;
    while ((mm = memberRe.exec(body)) !== null) {
      const protoMember = mm[1];
      if (protoMember.endsWith("_UNSPECIFIED")) continue;
      
      // Strip prefix: USERS_LAST_BILLED_TIMESTAMP → last_billed_timestamp
      const prefix = tableName.toUpperCase() + "_";
      const stripped = protoMember.startsWith(prefix)
        ? protoMember.slice(prefix.length).toLowerCase()
        : protoMember.toLowerCase();

      // Keep snake_case for data fields (backend expects it)
      fields.push({ name: stripped, type: "string", protoName: stripped });
    }

    if (fields.length > 0) {
      tableFields[tableName] = fields;
    }
  }

  return tableFields;
}

// ── Generate output ──

function generateFieldsFile(fields: Record<string, FieldEntry[]>, fileName: string): void {
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/gen-fields.ts — do not edit",
    'import { FieldRef } from "../fieldRef.ts";',
    "",
  ];

  for (const [key, entries] of Object.entries(fields)) {
    const name = key + "Fields";
    lines.push(`export const ${name} = {`);
    for (const e of entries) {
      lines.push(`  ${e.name}: new FieldRef<${e.type}>("${e.name}"),`);
    }
    lines.push("} as const;");
    lines.push("");
  }

  const outPath = path.join(OUT_DIR, fileName);
  fs.writeFileSync(outPath, lines.join("\n"), "utf-8");
  console.log(`Generated: ${outPath}`);
}

// ── Main ──

const queryFields = parseQueryFields();
generateFieldsFile(
  {
    sdkEvent: queryFields.sdkCall,
    aiToken: queryFields.aiToken,
    payment: queryFields.payment,
  },
  "query/fields.ts",
);

const dataFields = parseDataFields();
generateFieldsFile(dataFields, "data/fields.ts");

console.log("Codegen complete.");
